### ISSUE TITLE
Does not work with custom cards

### ISSUE THREAD

**Issue by julian-perge** [MADH95/DeckbuilderMod#1]
ScriptableObjectLoader​<​CardInfo​>.​allData​ ​=​ ​null​;

This line in DeckBuilderMod.cs causes non-vanilla cards to not be loaded into the card pool, making it impossible to use with custom cards and throwing An exception when CardLoader.GetCardByName is called.

**Comment by MADH95** [comment]
This was a workaround for an older version of API, where it would require that allData be null so cards could load. If you want to make a pull request I will merge
